version: '2'
services:
  apache:
    build: .
    ports:
      - "80:80" # web
      - "443:443"
      # - "35729:35729" # live reload
    volumes:
      - <app_container_name>-sync:/var/www/html:nocopy
      # - ./src:/var/www/html
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
      # - ~/.nvm:/var/www/.nvm
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - <app_container_name>-network

  db:
    image: mysql:5.6
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=<mysql_root_password>
      - MYSQL_DATABASE=<mysql_database>
      - MYSQL_USER=<mysql_user>
      - MYSQL_PASSWORD=<mysql_password>
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <app_container_name>-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=<mysql_root_password>
    ports:
     - 8080:80
    networks:
      - <app_container_name>-network
    depends_on:
      - db
    links:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <app_container_name>-network

networks:
  <app_container_name>-network:
    driver: bridge

volumes:
  <app_container_name>-sync:
    external: true
  dbdata:
    driver: local
