#!/usr/bin/env bash
scriptspath="$( cd "$(dirname "$0")" ; pwd -P )/scripts"

function helpme () {
  echo "Wrong usage: //TODO: Show help"
}

function install_platform () {
  if [ ! -z $1 ]; then
    bash "$scriptspath/$1/install"
  else
    helpme
  fi
}

function wrapup_platform () {
  if [ ! -z $1 ]; then
    bash "$scriptspath/$1/wrapup"
  else
    helpme
  fi
}

function run_command () {
  list="$(ls $scriptspath)"
  if [ ! -z $1 ]; then
    [[ $list =~ (^|[[:space:]])$1($|[[:space:]]) ]] && run_script $1 || helpme
  else
    helpme
  fi
}

function run_script () {
  bash "$scriptspath/$1"
}

case $1 in
  install)
    install_platform $2
    ;;
  wrapup)
    wrapup_platform $2
    ;;
  *)
    run_command $1
    ;;
esac
