#!/usr/bin/env bash

# General
php_version="7.0"

# Docker Configurations - Change according with your platform. Any values are accepted
#################### Opencart #########################
# Uncomment to install opencart and comment the others
# app_container_name="opencart"
# mysql_root_password="root"
# mysql_database="opencartdb"
# mysql_user="opencartuser"
# mysql_password="opencartpass"
#######################################################

#################### Prestashop #########################
# Uncomment to install prestashop and comment the others
# app_container_name="prestashop"
# mysql_root_password="root"
# mysql_database="prestashopdb"
# mysql_user="prestashopuser"
# mysql_password="prestashoppass"
#######################################################

#################### Woocommerce #########################
# Uncomment to install wordpress and comment the others
app_container_name="wordpress"
mysql_root_password="root"
mysql_database="wordpressdb"
mysql_user="wordpressuser"
mysql_password="wordpresspass"
#######################################################

# Just an animation to show loading dots while executing tasks
showLoading() {
  mypid=$!
  loadingText=$1

  echo -ne "$loadingText\r"

  while kill -0 $mypid 2>/dev/null; do
    echo -ne "$loadingText.\r"
    sleep 0.5
    echo -ne "$loadingText..\r"
    sleep 0.5
    echo -ne "$loadingText...\r"
    sleep 0.5
    echo -ne "\r\033[K"
    echo -ne "$loadingText\r"
    sleep 0.5
  done

  echo "$loadingText... DONE"
}


############################## Opencart ########################################
# Files to opencart Change if you want another version
# Access https://github.com/opencart/opencart/releases to find the available versions
opencart_download="https://github.com/opencart/opencart/releases/download/2.3.0.2/2.3.0.2-compiled.zip"

# Files to Mercado Pago Opencart module Change if you want another version
# Access  to find the available versions
opencart_mpmodule_download="https://github.com/mercadopago/cart-opencart/archive/master.zip"
opencart_mpmodule_version="v2.3"

################################################################################


############################## Prestashop ########################################
# Files to opencart Change if you want another version
# Access https://github.com/opencart/opencart/releases to find the available versions
prestashop_download="https://github.com/PrestaShop/PrestaShop/releases/download/1.6.1.18/prestashop_1.6.1.18.zip"

# Files to Mercado Pago Prestashop module Change if you want another version
# Access  to find the available versions
prestashop_mpmodule_download="https://github.com/mercadopago/cart-prestashop/archive/master.zip"
prestashop_mpmodule_version="v1.6.x"

################################################################################

############################## Woocommerce #####################################
# In order to install woocommerce, we need to install wordpress
# If you want to change wordpress version change the download link below.
# Access https://wordpress.org/ to find more about wordpress
wordpress_download="https://wordpress.org/latest.zip"

woocommerce_download="https://downloads.wordpress.org/plugin/projects-by-woothemes.1.5.0.zip"
woocommerce_mpmodule_download="https://github.com/mercadopago/cart-woocommerce/archive/master.zip"
################################################################################
