#!/usr/bin/env bash

rootpath="$( cd "$(dirname "$0")" ; pwd -P )/.."

(cd $rootpath && docker-compose stop)
(cd $rootpath && docker-sync stop)
(cd $rootpath && docker-compose down -v)
(cd $rootpath && docker-sync clean)
