#!/usr/bin/env bash

filepath="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -z "$1" ]; then
  (cd $filepath/.. && docker-compose exec --user www-data apache bash)
else
  (cd $filepath/.. && docker-compose exec --user $@ apache bash)
fi
