#!/usr/bin/env bash

# General
php_version="7.0"

# Docker Configurations - Any values are accepted

export app_container_name="magento"
export mysql_root_password="root"
export mysql_database="magentodb"
export mysql_user="magentouser"
export mysql_password="magentopass"

admin_firstname="Magento"
admin_lastname="Test"
admin_email="magento.test@example.com"
admin_user="admin"
admin_password="admin123"
language="pt_BR"
currency="BRL"
timezone="America\/Sao Paulo"
backend_frontname="admin"
