#!/usr/bin/env bash
filepath="$( cd "$(dirname "$0")" ; pwd -P )"
scriptspath="$filepath/.."
srcpath="$scriptspath/../src"

source "$filepath/configs"
source "$scriptspath/loadingfun"

echo "Magento installation. This may take a while!"

# Copying inserting magento version to installation_script
cp $filepath/install_magento $srcpath

sed -i '' -e "s/<mysql_database>/$mysql_database/g;
              s/<mysql_user>/$mysql_user/g;
              s/<mysql_password>/$mysql_password/g;
              s/<admin_firstname>/$admin_firstname/g;
              s/<admin_lastname>/$admin_lastname/g;
              s/<admin_email>/$admin_email/g;
              s/<admin_user>/$admin_user/g;
              s/<admin_password>/$admin_password/g;
              s/<language>/$language/g;
              s/<currency>/$currency/g;
              s/<timezone>/$timezone/g;
              s/<backend_frontname>/$backend_frontname/g" $srcpath/install_magento

chmod a+x $srcpath/install_magento

mkdir $srcpath/magento2

# Config docker environment
bash $scriptspath/init

bash $scriptspath/start_build
