#!/usr/bin/env bash
filepath="$( cd "$(dirname "$0")" ; pwd -P )"
scriptspath="$filepath/.."
srcpath="$scriptspath/../src"

source "$scriptspath/configs"

echo "Opencart installation. This may take a while!"

# Download and copy Opencart files to src directory
mkdir $filepath/opencart
(cd $filepath/opencart && wget -q $opencart_download) & showLoading "Downloading Opencart"
(cd $filepath/opencart && unzip -q ${opencart_download##*/}) & showLoading "Extracting ${opencart_download##*/}"
cp -rp $filepath/opencart/upload/* $srcpath & showLoading "Coping files to src folder"
rm -rf $filepath/opencart

# Config docker environment
bash $scriptspath/init

# Config opencart installation
(rm $srcpath/config-dist.php && \
 rm $srcpath/admin/config-dist.php && \
 cp $scriptspath/../config/opencart/base_config.php $srcpath/config.php && \
 cp $scriptspath/../config/opencart/admin_config.php $srcpath/admin/config.php && \
 sed -i '' -e "s/<mysql_database>/$mysql_database/g;s/<mysql_user>/$mysql_user/g;s/<mysql_password>/$mysql_password/g" $srcpath/config.php && \
 sed -i '' -e "s/<mysql_database>/$mysql_database/g;s/<mysql_user>/$mysql_user/g;s/<mysql_password>/$mysql_password/g" $srcpath/admin/config.php) & showLoading "Coping config files"

# Installing MercadoPago plugin

# Download and extract mp plugin
filename="${opencart_mpmodule_download##*/}"
mkdir $filepath/mp_opencart
(cd $filepath/mp_opencart && wget -q $opencart_mpmodule_download) & showLoading "Downloading MercadoPago Module"
(cd $filepath/mp_opencart && unzip -q $filename) & showLoading "Extracting $filename"

# Copy files to src folder
(cp -R $filepath/mp_opencart/cart-opencart-`echo "$filename" | cut -d'.' -f1`/$opencart_mpmodule_version/* $srcpath) & showLoading "Coping mp module files to src folder"
rm -rf $filepath/mp_opencart

bash $scriptspath/start_build
