#!/usr/bin/env bash

# General
php_version="7.0"

# Docker Configurations - Any values are accepted

export app_container_name="magento"
export mysql_root_password="root"
export mysql_database="magentodb"
export mysql_user="magentouser"
export mysql_password="magentopass"

magento_version="1.9"
admin_firstname="Magento"
admin_lastname="Test"
admin_email="mage/nto.test@example.com"
admin_user="admin"
admin_password="admin123"
language="pt_BR"
currency="BRL"
timezone="America/Sao Paulo"
backend_frontname="admin"



# Files to magento Change if you want another version
# Access https://github.com/PrestaShop/PrestaShop/releases to find the available versions
magento_download="https://github.com/PrestaShop/PrestaShop/releases/download/1.6.1.18/magento_1.6.1.18.zip"

# Files to Mercado Pago Prestashop module Change if you want another version
# Access  to find the available versions
magento_mpmodule_download="https://github.com/mercadopago/cart-magento/archive/master.zip"
magento_mpmodule_version="v1.6.x"
